name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@0ba3f6b8907da080154872a6ed9e103a1cb46852 # v2025.05.17.02
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
